### ISSUE TITLE
Async validation

### ISSUE THREAD

**Issue by femanso** [cristijora/vue-form-wizard#1]
Is there any way I can do async validation? vue-form-generator recently added promise based validators but I can't get it working with beforeChange.
The validator works, but since beforeChange is not receiving false, i can go to the next step without restriction.

By the way, thanks for the repo, saved me a lot of time.

**Comment by cristijora** [comment]
As you already saw, async validation is not supported. It's a good idea actually to have it and support that since it might be a common use case. I will try to implement something promise based and come back with an example.

**Comment by femanso** [comment]
I could get it working, but made too many changes to fit my project, a pull request would break the module since I took out some functions. Thats what I did for the async validation:

on FormWizard.vue, 
changed `beforeTabChange(index)` to return a promise:
```
    beforeTabChange(index) {
      let oldTab = this.tabs[index]
      if (oldTab && oldTab.beforeChange !== undefined) {
        return oldTab.beforeChange()
      }
      return Promise.resolve()
    }
```

`nextTab()` function now uses then/catch and have a loading state:
```
    nextTab() {
      this.isLoading = true
      this.beforeTabChange(this.activeTabIndex).then(() => {
        this.isLoading = false
        if (this.activeTabIndex < this.tabCount - 1) {
          this.activeTabIndex++
          this.increaseMaxStep()
          this.checkStep()
        } else {
          this.isLastStep = true
          this.$emit('finished')
        }
      }).catch(() => {
        this.isLoading = false
      })
    },
```

finally i can now send a promise as the `beforeChange` function, and change the validator manually

```
        beforeChange: () => {
          return new Promise((resolve, reject) => {
            api.post('/xxxx/', {
              url: this.model.url
            }).then(response => {
              if (response.data && response.data.success !== false) {
                return resolve()
              }
              this.$refs.steps[1].fields[0].validator = () => {
                return ['Error message']
              }
              this.$refs.steps[1].validate()
              return reject()
            }).catch(err => {
              return reject(err)
            })
          })
        }
```
this last part looks pretty bad, but I couldnt get it working by setting a promise to vfg validator. 
I think there are better ways to achieve that, I'll post here if I get a better solution.

**Comment by cristijora** [comment]
This definetely can be done in a cleaner way. I will try to come up with an example today or tomorrow.

**Comment by SirRafaMedina** [comment]
+1

**Comment by cristijora** [comment]
Still testing this out but the usage  would be a promise that resolves with `true`
```js
//template
:before-change="validateAsync"

validateAsync () {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            resolve(true)
          }, 1000)
        })
      },
```
The validation would fail if the promise is rejected or if the resolved value is false
You can test with the generated [js build file](https://github.com/cristijora/vue-form-wizard/blob/1-async-validation/dist/vue-form-wizard.js) until I manage to fully test this

**Comment by femanso** [comment]
sounds good, validation could also be a separate function, beforeChange working as a middleware and something like 'stepValidation' working as a real validation system for the step, this way you can have visual control of the steps errors.

**Comment by cristijora** [comment]
I made a PR and marked the function which handles async beforeChange. 
Can you provide like a sketch of the final output you would expect? Didn't quite get your point

**Comment by cristijora** [comment]
Updated README with an [example](https://jsfiddle.net/bt5dhqtf/272/) of async validations. @femanso Please detail your last comment and provide some code of how you expect it to be.

**Comment by femanso** [comment]
I've just tested it, it works as expected. I made a small change for the errors messages, using reject('some field is required') instead of just reject, and showing it on a slot (inside the TabContent), also adding class 'is-error' to the icon. I'll send a pr and you can use it if you like.
I think you can close this, thanks!

**Comment by Lirianer** [comment]
When will this feature be available through npm?

**Comment by cristijora** [comment]
@Lirianer this one is on npm from like 10 months ago

**Comment by Lirianer** [comment]
Oh, I'm sorry. 
I was having a problem when setting before-change to a function with a parameter returning a promise , `:before-change=validateTab(1)` it said it was expecting a function but it got a promise instead, and when I came to check I read in the ReadMe that the async wasn't in npm. 
Tough now I've read again and it may be that the async with error message isn't present yet.

Still, I did got the event to work by using an anonymous function returning the function.

Sorry for bothering!

**Comment by cristijora** [comment]
@Lirianer actually good point there. Readme was out of date. I think it was never updated 😆 

You can pass params to the validation functions, but it works if you wrap them in an arrow function
`:before-change="() => validate(someParam)"`
https://jsfiddle.net/bt5dhqtf/2092/
