### ISSUE TITLE
browser back situation

### ISSUE THREAD

**Issue by gyamxxx** [cristijora/vue-form-wizard#10]
Hi, I'm trying vue-route example.
https://jsfiddle.net/bt5dhqtf/267/
First, I press next button, Next I press browser back button, then It does not show anymore.
How can it show first page when going back to top?

**Comment by cristijora** [comment]
I see the issue. I will try to do something about it in the following days. Ideally back button should work and redirect you to the previous tab. Most likely I have to add a route watcher

**Comment by gyamxxx** [comment]
I see. You can do this.

**Comment by cristijora** [comment]
I am working on this. It's a bit tricky but hopefully it will be solved soon. Also noticed that refreshing while being on a certain step, redirects to first step

**Comment by cristijora** [comment]
@gyamxxx Please check the initial fiddle. back and forward buttons should now trigger tab changes

**Comment by gyamxxx** [comment]
@cristijora 
Thank you for fix it.
but, same problem is occurring(First, I press next button, Next I press browser back button, then It does not show anymore)..
Is this correct url?
https://jsfiddle.net/bt5dhqtf/267/

**Comment by cristijora** [comment]
Does this also happen locally ? I can't really see the routes in jsfiddle so it's a bit hard to understand what actually happens there. At least it's good that tab switching works when going back and forward in the browser.
I will see if this happens locally which I think it doesn't and figure out the issue

**Comment by gyamxxx** [comment]
It work well at local without ```mode:'history```.
Thank you very much.
