### ISSUE TITLE
bootstrap button classes affected

### ISSUE THREAD

**Issue by genesluna** [cristijora/vue-form-wizard#11]
When we use slots for the navigation buttons, we cannot style them with bootstrap classes.

https://jsfiddle.net/genesluna/30v2q7uc/5/

**Comment by cristijora** [comment]
Thanks for posting @genesluna I already know about this issue and its basically the same as #9 
I am working on and almost have a full solution which has very specifi class names such as wizard-btn instead of btn. If you have any suggestions or ideas, I am open to them

**Comment by cristijora** [comment]
Please check the same fiddle but with the js and css sources from the `dev` branch which contains the modifications regarding this part
https://jsfiddle.net/30v2q7uc/6/

**Comment by genesluna** [comment]
It seems pretty good to me. Thank you so much.

**Comment by webdevnerdstuff** [comment]
Please add a prop so we can pass in our own classes to the buttons.

**Comment by cristijora** [comment]
@webdevnerdstuff you can use slots and use your owm buttons or add classes on top of the existing ones. See the examples from readme page.

**Comment by webdevnerdstuff** [comment]
Ok I figured out where I was getting stuck. I'm not sure if it's because of our setup for the form, or if the documentation is off. But this solved my problem. Thanks for the quick response. :)

```
<template slot="footer" slot-scope="props">
```
Should be
```
<template slot="footer" scope="props">
```

AKA... RTFM better :)

**Comment by cristijora** [comment]
From vue > 2.5 it changed from `scope` to `slot-scope`. I, put `slot-scope` in the docs because most of the developers already use vue 2.5+. Will maybe add a notice there on this part

**Comment by webdevnerdstuff** [comment]
You have it in your Compatibility section, I think it was more my lack of reading that part fully, not your documentation.
