### ISSUE TITLE
Keyup enter event to change tab

### ISSUE THREAD

**Issue by richardgvas** [cristijora/vue-form-wizard#122]
Hi there. Maybe this is a simple question but I'm trying to apply the keyup enter event in order to change to the next tab, but I can't find the way. I was trying to implement it in the template footer but there is no way: 
```
<template slot="footer" slot-scope="props">
       <div class="wizard-footer-left">
           <wizard-button  v-if="props.activeTabIndex > 0 && !props.isLastStep" :style="props.fillButtonStyle">Previous</wizard-button>
        </div>
        <div class="wizard-footer-right">
          <wizard-button v-if="!props.isLastStep"@keyup.enter="props.nextTab()" class="wizard-footer-right" :style="props.fillButtonStyle">Next</wizard-button>

          <wizard-button v-else @keyup.enter="alert('Done')" class="wizard-footer-right finish-button" :style="props.fillButtonStyle">  {{props.isLastStep ? 'Done' : 'Next'}}</wizard-button>
        </div>
</template>
```

thanks in advance.

**Comment by cristijora** [comment]
Hey @richardgvas 
If you want to use the enter event, you need a form and use `@submit.prevent` 
https://codesandbox.io/s/ry4q2o96no

Enter event is supported by form and inputs so there are not many alternatives here
