### ISSUE TITLE
Question: Pass info between steps

### ISSUE THREAD

**Issue by mr337** [cristijora/vue-form-wizard#128]
I am starting to use the wizard and having a design question on how to pass info between steps. For example step 1, we use to get the ID of an object. In step 2 we want to load that object based on the info from step 1.

Not for sure what the best design to do that since children components don't normally talk to each other. There are some work around such as calling up with events and passing as props but that seems clunky.

Any thoughts?

**Comment by cristijora** [comment]
Hey @mr337 The wizard doesn't come with any solution on this part. It's pretty much up to you if you use a global state or pass events from a step to another. I'd suggest having an individual component for each step and keep the necessary objects in the parent component where the wizard is located. I have an example somewhere in my projects. Will search for it and try to build a codesandbox demo so you get a better idea on how to do it easier.

**Comment by mr337** [comment]
I appreciate it. Just to follow up on the implementation, pass info from parent component to each step via props and then have info passed back up on custom events? (https://vuejs.org/v2/guide/components.html#Using-v-on-with-Custom-Events)

Each step can post update an object on the backend API side, and then signal to the parent to refresh the object, this way the parent is always in sync with each of the steps?

**Comment by cristijora** [comment]
@mr337 It can be much simpler than that.
You can simply call validation methods within child and emit events. https://codesandbox.io/s/l9mz5zn7yz

If you don't need validations in some components you could simply emit an event in each child component and in the parent merge the data.

**Comment by mr337** [comment]
Thanks!
