### ISSUE TITLE
How to integrate `Element UI`?

### ISSUE THREAD

**Issue by thearabbit** [cristijora/vue-form-wizard#13]
How to integrate `Element UI`?

**Comment by cristijora** [comment]
You can use slots and place pretty much anything you want inside tabs. 
Here is an example https://jsfiddle.net/bt5dhqtf/393/ where in the second tab you have an Element UI form and the `prev` `next` buttons are also from element ui.
You can also customize the title and sub-title with slots. See slot names [here](https://github.com/cristijora/vue-form-wizard#slots)

**Comment by thearabbit** [comment]
Thanks for your reply.
I will try soon 👍

**Comment by thearabbit** [comment]
Excuse me, Could you example with setting a `Form` for any `Step`?
(not only step)
