### ISSUE TITLE
Hiding tab-content and showing it back doesn`t keep it`s position index 

### ISSUE THREAD

**Issue by Al3xR0** [cristijora/vue-form-wizard#137]
I'm trying to dynamically hide a tab-content based on an option (`<tab-content v-if="foo === 'bar'" ...`), and the tab gets hidden. If I turn off the option the tab reappears but it doesn't keep it's position (initial tab position is 3/6, after reappearing it's 6/6). How can I fix this ?

**Comment by cristijora** [comment]
Hi @Al3xR0 If you want predictable tabs, you have to use `v-for` and again `key` each tab. 
https://jsfiddle.net/bt5dhqtf/1697/
