### ISSUE TITLE
Generic type 'Promise<T>' requires 1 type argument(s)

### ISSUE THREAD

**Issue by Capellan29** [cristijora/vue-form-wizard#144]
In the tab content type, for typescript support, the beforeChange method returns a boolean or a promise, but the promise needs a type argument like "Promise<boolean>".
<img width="476" alt="screen shot 2017-12-27 at 9 25 57 am" src="https://user-images.githubusercontent.com/18630416/34382881-fef66dd6-eae7-11e7-87ab-29f6379ca38e.png">
I fixed it, using the boolean type for the promise, but is nice to have it fixed for a future release.
<img width="594" alt="screen shot 2017-12-27 at 9 27 36 am" src="https://user-images.githubusercontent.com/18630416/34382935-487ee208-eae8-11e7-975f-4290b44b134d.png">

**Comment by cristijora** [comment]
Thanks @Capellan29 for pointing out.
My experience with TS basically started with this component 😄 
If you have time feel free to open a PR and I will merge it since the fix is minor

**Comment by Capellan29** [comment]
@cristijora I did it, an update to the npm package with this change will make me so happy.
And thanks for this componen, is really great.

**Comment by cristijora** [comment]
Released [0.8.2](https://github.com/cristijora/vue-form-wizard/releases/tag/v0.8.2)

**Comment by Capellan29** [comment]
Thanks.
