### ISSUE TITLE
Pressing outside the next button, triggers back button

### ISSUE THREAD

**Issue by serge20** [cristijora/vue-form-wizard#15]
I've tried implementing this and i'm wondering if the expected behavior of pressing the empty space between back and the next button should trigger a back button?

**Comment by cristijora** [comment]
Thanks for pointing this out. This is indeed not intended behavior.  I will fix it

**Comment by cristijora** [comment]
I fixed this. You can check one of the fiddles from readme/docs and see if it's ok now. I will also publish a new npm version soon

**Comment by cristijora** [comment]
Released on npm under 0.4.2 -> https://github.com/cristijora/vue-form-wizard/releases/tag/v0.4.2
