### ISSUE TITLE
Deactivate a tab after a user has proceeded from there?

### ISSUE THREAD

**Issue by mirikerstein** [cristijora/vue-form-wizard#152]
Hello,

Thanks for a fantastic package. I'd like my wizard to flow such that there is "no going back." I have customized the footer buttons to disable the previous button where I'd like to, but the user can still transition to a previous step by clicking that tab on the top tab bar. How can I disable a tab on the top bar once a user has proceeded from there?

Thank you!

**Comment by cristijora** [comment]
Hi @mirikerstein 
There is an option to customize the steps with a scoped slot.
Here is the reference http://vuejs.creative-tim.com/vue-form-wizard/#/?id=step-slot
By default (with the scoped slot override) the steps are not clickable unless you specify a `@click` handler for them.

https://jsfiddle.net/CristiJ/bt5dhqtf/1744/

I guess that's pretty much what you need there

**Comment by mirikerstein** [comment]
Thank you!
