### ISSUE TITLE
Dynamic step injection?

### ISSUE THREAD

**Issue by Eencsio** [cristijora/vue-form-wizard#158]
Hi! cristijora

Is it possible to inject a dynamic number of steps to the form?
For example, adding more steps depending on the response of a user in a previous step

Thanks

**Comment by cristijora** [comment]
@Eencsio That should be possible but requires that all the steps are rendered with a `v-for` which means you have to use `component :is="componentName"`

You can find an example under "Dynamic components for tabs" in readme https://jsfiddle.net/bt5dhqtf/1800/
