### ISSUE TITLE
Skip a tab content

### ISSUE THREAD

**Issue by serge20** [cristijora/vue-form-wizard#16]
Hi,

I was wondering what's the best way to skip a tab and jump directly to a specific tab of your choice.

My use case is the following:

we have 4 tab contents, you make a payment on tab 2 which gets validated before you can go to tab 3. However in the case of the form right now, you're able to press on the tabs and go back to them. If you go back to tab 2, it will always try to validate and send to tab 3, is there any way to send it to tab 4 from tab 2? 

Thanks,

**Comment by cristijora** [comment]
There is an internal method for such situations
https://jsfiddle.net/bt5dhqtf/448/

```
changeTab (oldIndex, newIndex) 
```
Usage: 
```
<form-wizard ref="wizard">
</form-wizard>

this.$refs.wizard.changeTab(0,3)
```
