### ISSUE TITLE
Cannot make axios request before-change event

### ISSUE THREAD

**Issue by ScriptMint** [cristijora/vue-form-wizard#162]
Hello,
I was trying to post axios request when click on 'Next' button i.e. on before-change event, however it throws below error:
![error](https://user-images.githubusercontent.com/31760604/34906220-edc4bd06-f88e-11e7-8018-4dc91c26db4b.jpg)

Here is my Vue component

`<tab-content :before-change="validate">Hello</tab-content>`

`
    validate(){
        axios.post('/api/validate',this.form)
        .then(response => {
            return true;
        })
        .catch(error => {
            return false;
        })
    }
`

Is there something that we cannot make axios request on this event?

**Comment by ScriptMint** [comment]
Hey...i just figured it out...

Thanks for wonderful package!

**Comment by zaqpiotr** [comment]
Hello @ScriptMint can You please share Your solution?

**Comment by essramos** [comment]
Also having this issue. Can you share your solution? @ScriptMint or @cristijora any help?

**Comment by lexjwa** [comment]
I am unable to return true or false from .then and .catch in case of success and error respectively of axios call to API.

**Comment by twin250** [comment]
hi @lexjwa , @essramos , @zaqpiotr . I found a fix by putting the axios call in a promise. Using the example request above, this is what I did: 

{ 
 return new Promise((resolve, reject) => { 
    axios.post('/api/validate',this.form) 
    .then(response => { resolve(true) }) 
    .catch(error => { reject(false) }) }
})
}
