### ISSUE TITLE
changing Icon after step is completed

### ISSUE THREAD

**Issue by Ghsthawk** [cristijora/vue-form-wizard#182]
Any way to do this now? I keep trying with before change function but I am new to Vue and can't seem to be able to do it.

**Comment by cristijora** [comment]
Hi @Ghsthawk 
This is not really documented but you can pass an additional object to each tab
`additional-info` which can contain anything you need

```html
 <tab-content title="Additional Info" icon="ti-settings"
                        :additional-info="{activeIcon: 'ti-hand-point-down'}">
        My second tab content
      </tab-content>
```
Later on you could access it via scoped slots. 

```html
<wizard-step slot-scope="props" slot="step" :tab="props.tab" :index="props.index">
      
        <i slot="active-step" :class="props.tab.additionalInfo.activeIcon" class="wizard-icon"></i>
      </wizard-step>
```
https://jsfiddle.net/bt5dhqtf/1927/
