### ISSUE TITLE
How reset wizard?

### ISSUE THREAD

**Issue by yblancof2** [cristijora/vue-form-wizard#183]
I need know how component wizard can be reset on method onComplete. Regards

**Comment by cristijora** [comment]
Hello @yblancof2 
There is an [internal reset method](https://github.com/cristijora/vue-form-wizard/blob/master/src/components/FormWizard.vue#L260) you can call via refs.
https://github.com/cristijora/vue-form-wizard/blob/master/src/components/FormWizard.vue#L260
