### ISSUE TITLE
Foundation instead of Bootstrap?

### ISSUE THREAD

**Issue by maxcook** [cristijora/vue-form-wizard#186]
How can i change the look of the form for Foundation based website instead of Bootstrap?
My first approach ist to try to set the bs_variables in the corresponding file to appear as close as possible as Foundation.
What else has to be done?

**Comment by cristijora** [comment]
Hi @maxcook Do you want to give it a different look or what exactly?
The component has it's own css and is not really bootstrap based. You can see in the examples that bootstrap is not imported.
