### ISSUE TITLE
Bootstrap Modal

### ISSUE THREAD

**Issue by saidrr46** [cristijora/vue-form-wizard#187]
How to use it inside bootstrap modal ?

**Comment by cristijora** [comment]
@saidrr46 Do you use a Vue library for bootstrap ?
If yes, you would declare it in the modal content.
Here is an example with bootstrap-vue
https://jsfiddle.net/bt5dhqtf/1954/

**Comment by allaghi** [comment]
How about if I am using bootstrap and Vue library for bootstrap ?
