### ISSUE TITLE
How to pass props to route?

### ISSUE THREAD

**Issue by mrcasual** [cristijora/vue-form-wizard#19]
Re,

I am rendering a wizard within a component that receives props:

`<wizard :data='....'></wizard>`

Inside the component, I am using your sample [router integration code](https://jsfiddle.net/bt5dhqtf/267/):

```
<tab-content title="First Step" route="/first_step">
</tab-content>
....
```

`first_step` is mapped to another component:

```
const first_step = Vue.component('first_step', require('./first_step.vue'));
const router = new VueRouter({
  routes: [
    { path: '/first_step', component: first_step }
  ]
});
```
Question: how do I pass `data` received by the wizard component to the component loaded inside the tab (other than using `this.$parent.$parent.data` inside the `first_step` component)?

Thanks.

**Comment by cristijora** [comment]
Unfortunately I don't think Vue-router allows passing props dynamically. From what I know you can pass props to routes only in the initialization (inside `new VueRouter`) If you know how to do that dynamically please make a fiddle and I will try to see if it's possible to do it in the wizard.
