### ISSUE TITLE
make circle color and text color separate

### ISSUE THREAD

**Issue by bombomtsao** [cristijora/vue-form-wizard#215]
Hi,
Is it possible to make color of circle and text different?
For example, the step1 icon is red, but the "step 1" text is in black

Thanks~

**Comment by cristijora** [comment]
You could use css or the `step` slot for that. 
https://jsfiddle.net/bt5dhqtf/2378/

The only disadvantage is that you have to use `!important` to override the inline styles for the text color

Option with step slot will not use `!important`
https://jsfiddle.net/bt5dhqtf/2387/

**Comment by TuringJest** [comment]
I wonder about the reasoning behind hardcoding inline styles without an option to disable them...
