### ISSUE TITLE
preventDefault for onKeyPress enter

### ISSUE THREAD

**Issue by nxmohamad** [cristijora/vue-form-wizard#218]
how can I prevent the page from refreshing when the user presses enter when having an input in focus?

is this resolved through Vue's API instead? I apologise if so.

**Comment by cristijora** [comment]
Yep this would be with Vue API.
https://vuejs.org/v2/guide/events.html#Event-Modifiers

`<form @submit.prevent>` to prevent form from making a request (reloading)
Will close the task since this is not related to form wizard :)

**Comment by nxmohamad** [comment]
thanks!
