### ISSUE TITLE
Disable clickable tabs

### ISSUE THREAD

**Issue by Omazon** [cristijora/vue-form-wizard#220]
The tabs are clickable for default, exists any way to disabled that function??.

**Comment by cristijora** [comment]
You can use the step slot http://vuejs.creative-tim.com/vue-form-wizard/#/?id=step-slot

and have full control over the step behavior. This example doesn't have clickable tabs

https://jsfiddle.net/bt5dhqtf/2681/

**Comment by yogithesymbian** [comment]
how to make clickable ? any option ? i didnt find out. i looking for clickable without next button so we can bypass step.

1. step 1 ( first open page i here )
2. step 2 ( cant click ) , its can be click after click next button
3. step 3 ( cant click ) i looking for click able

**"vue-form-wizard": "0.8.4",**
