### ISSUE TITLE
How can I navigate between step without using the tab

### ISSUE THREAD

**Issue by 1112403** [cristijora/vue-form-wizard#223]
Hi there,
Is there any function that I can use to navigate between tabs ?
For example: 
I want to go to tab 1 from tab 4
   changeTab(1)

Thanks

**Comment by cristijora** [comment]
Yes, please see in the docs 
http://vuejs.creative-tim.com/vue-form-wizard/#/?id=methods

changeTab(oldIndex, newIndex) - Navigates from one tab to another. Note that this method does not trigger validation methods. Use it with caution!

`<form-wizard ref="wizard">`

`this.$refs.wizard.changeTab(1, 3)`

**Comment by cpvbruno** [comment]
@cristijora  I cant navigate through navigation buttons after I used this.$refs.wizard.changeTab(1, 3)
