### ISSUE TITLE
Validation of fields at each step

### ISSUE THREAD

**Issue by marcelloinfoweb** [cristijora/vue-form-wizard#227]
How would I do to validate each field in each step of the form so in the end I send it to a database?

**Comment by cristijora** [comment]
@marcelloinfoweb Please see some of the examples from readme for that
Element UI validation https://codesandbox.io/s/l9mz5zn7yz

The idea is to use `:before-change` callback on steps and handle your validation within those functions. 
before changes basically blocks navigation until it returns `true` or a promise that resolves with `true`
https://jsfiddle.net/bt5dhqtf/105/

**Comment by tarekadam** [comment]
I had a better idea... and by "better" I mean "different".  I was struggling with this issue in my implementation of vue-form-wizard with Element UI integration.  To solve this into step-by-step validation while still harnessing the power of all the pre-existing validation logic...

`<form-wizard @on-complete="totallyReady"...`
`<tab-content :before-change="function(){ return validate('el-form-ref-' + index, _.pick(rules, ['input_a','input_b'])) }" ...`
`<el-form :ref="'form-ref-' + index" ...`

Method
```
validate: function (ref, rules) {
        var step = this.$refs[ref][0]
        step.rules = rules;
        return step.validate()
      }
```
