### ISSUE TITLE
Finish Now functionality

### ISSUE THREAD

**Issue by SmarterPhoneLabs** [cristijora/vue-form-wizard#228]
We have been successfuly using VFW for a few months now in our app and like it very much.
However, one request we get from users a lot is the ability to have a "Finish Now" option.
Many of our steps in our wizard offer optional settings for our users, and they have to click through sometimes 5-6 steps to get to the finish button.

Any help with this would be greatly appreciated,

**Comment by cristijora** [comment]
Hi @SmarterPhoneLabs Thanks for the feedback there.

You could customize the footer with scoped slots or have a separate button apart from the footer and use `nextTab` function to navigate until the end.

https://jsfiddle.net/bt5dhqtf/2891/

**Comment by SmarterPhoneLabs** [comment]
Thanks for the reply and the fiddle, I will give it a try and see if I can make that work for me too.

**Comment by SmarterPhoneLabs** [comment]
I have tried to get this working in my code, but I get vue Warn errors that "props" is not defined

![image](https://user-images.githubusercontent.com/1190629/37781701-37f55af6-2dbf-11e8-9912-1f15b73a27d9.png)

**Comment by cristijora** [comment]
Did you add this part 
`<template slot="footer" slot-scope="props">`
Also do you mind telling what version of Vue you use ?
If it's below 2.5 you might need to use `scope="props"` instead of `slot-scope`

**Comment by SmarterPhoneLabs** [comment]
OK Im on an older version of Vue (2.1)
Im also using vue-form-wizard 0.4.2 (older I know, but we had to modify it)
Changing to scope="props" cleared the error,

But the buttons do not render.
Here is a capture of my code:
![image](https://user-images.githubusercontent.com/1190629/37782481-f7716ed2-2dc0-11e8-9689-3cf72be5fd19.png)

**Comment by cristijora** [comment]
That might be because of the older version of wizard which didn't contain buttons as separate components. Try with some simple buttons 
`button` first and see if that works.

**Comment by SmarterPhoneLabs** [comment]
sorry, No such luck

**Comment by SmarterPhoneLabs** [comment]
Just wanted to follow up here and let you know, I was finally able to finish our upgrade to Vue 2.5 and thus able to get this to work for us, thanks
