### ISSUE TITLE
support for toggle tab based on data

### ISSUE THREAD

**Issue by rahul1235** [cristijora/vue-form-wizard#229]
There should be an option to hide/show tabs based on data property.

**Comment by cristijora** [comment]
Not sure I understood @rahul1235 but this seems more like a `tab` functionality rather than a wizard one

**Comment by rahul9874563210** [comment]
@cristijora  Sorry for the late response. 
example https://jsfiddle.net/enigmatic/bt5dhqtf/3086/

in the above example if want to toggle next tab then it the positioning of target tab(in this case 3rd tab) gets changes. 
any workaround for this ??
the tabs json is  like this:
```javascript
{
  tabs: [
    {
      title: 'Personal details',
      icon: 'ti-user',
      component: 'step1',
      hide: false
    },
    {
      title: 'Is Logged In?',
      icon: 'ti-settings',
      component: 'step2',
      hide: true
    },
    {
      title: 'Additional Info',
      icon: 'ti-location-pin',
      component: 'step3',
      hide: false
    },
    {
      title: 'Last step',
      icon: 'ti-check',
      component: 'step4'
    },
    
  ],
}
```
if i want to toggle step3 componenet its does that but it adds it after step 4 which is not good.

SORRY again for the late reply

**Comment by rahul1235** [comment]
@cristijora  Sorry for the late response. 
example https://jsfiddle.net/enigmatic/bt5dhqtf/3086/

in the above example if want to toggle next tab then it the positioning of target tab(in this case 3rd tab) gets changes. 
any workaround for this ??
the tabs json is  like this:
```javascript
{
  tabs: [
    {
      title: 'Personal details',
      icon: 'ti-user',
      component: 'step1',
      hide: false
    },
    {
      title: 'Is Logged In?',
      icon: 'ti-settings',
      component: 'step2',
      hide: true
    },
    {
      title: 'Additional Info',
      icon: 'ti-location-pin',
      component: 'step3',
      hide: false
    },
    {
      title: 'Last step',
      icon: 'ti-check',
      component: 'step4'
    },
    
  ],
}
```
if i want to toggle step3 componenet its does that but it adds it after step 4 which is not good.

SORRY again for the late reply

**Comment by cristijora** [comment]
Hey @rahul1235 This can be done if you use `v-for` and explicit `keys` so Vue can render the slots predictably. Here is a demo 
https://jsfiddle.net/enigmatic/bt5dhqtf/3086/

**Comment by makroxyz** [comment]
it doesn't work!!

https://jsfiddle.net/enigmatic/bt5dhqtf/3086/

the toggle button hides tab on first click, but on second it adds the tab at the end!

I can't face this issue! any other workaround??
