### ISSUE TITLE
[Question] Is there a way to dynamically change to a tab?

### ISSUE THREAD

**Issue by hawkeye64** [cristijora/vue-form-wizard#23]
For instance, the last tab contains a summary of the previous tabs and if user sees something and would like to edit it, I'd like to have a button on the summary tab that allows the user to go to the correct tab rather than traverse back.

**Comment by cristijora** [comment]
There have been 2 issues around this.
https://github.com/cristijora/vue-form-wizard/issues/16

> There is an internal method for such situations
https://jsfiddle.net/bt5dhqtf/448/

```
changeTab (oldIndex, newIndex) 
```
Usage: 
```
<form-wizard ref="wizard">
</form-wizard>

this.$refs.wizard.changeTab(0,3)
```
