### ISSUE TITLE
ti icons are not showing

### ISSUE THREAD

**Issue by fazila-rahman** [cristijora/vue-form-wizard#234]
The code i am using is:

> 
<form-wizard title="Client Files" subtitle="" color="#80aaff" error-color="#ff4949" shape="circle" transition="bounce" @on-complete="onComplete" @on-loading="" @on-validate="" ref="wizard">
        <tab-content title="File Info"   icon="ti-user">
                 
          </tab-content> .....
<tab-content title="Trust Statement"  icon="ti-check">
                 
          </tab-content>
    </form-wizard>
But, icons are not showing .... please see the image below.
![ti-icons](https://user-images.githubusercontent.com/4983805/38771303-3974df06-3fde-11e8-8db3-b01c5e989c4d.JPG)

I have imported css files too:
`import {FormWizard, TabContent} from 'vue-form-wizard'
    import 'vue-form-wizard/dist/vue-form-wizard.min.css'`

Is there anything I am missing? Please help!

**Comment by wa05** [comment]
same error here.. did you solve this @synfony  ?

**Comment by wa05** [comment]
import themify into the project.. or use fontAwesome

**Comment by kopiaman** [comment]
add css first
`<link
      rel="stylesheet"
      href="https://unpkg.com/@icon/themify-icons/themify-icons.css"
    />
`

then...
`
<tab-content title="calendar" icon="ti ti-calendar">
         ...you content...
        </tab-content>
`
