### ISSUE TITLE
Error in mounted hook: this.addTab is not a function

### ISSUE THREAD

**Issue by msambarino** [cristijora/vue-form-wizard#237]
Hi there, first of all, thanks for putting in the work to create this library, much appreciated.

I'm getting the following error:

```
Error in mounted hook: "TypeError: this.addTab is not a function. (In 'this.addTab(this)', 'this.addTab' is undefined)"
```

I'm registering the components globally like this:

```javascript
import Vue from 'vue/dist/vue'
import VueFormWizard from 'vue-form-wizard'

Vue.use(VueFormWizard);
```

Do you have any idea what could i be doing wrong to point me in the right direction?

Thanks in advance!

**Comment by msambarino** [comment]
Closing as this was an error on my part.

**Comment by frostfire64** [comment]
@msambarino, do you by any chance remember how you solved that issue? It seems that I may have made the same mistake.

**Comment by frostfire64** [comment]
The reason for the mistake was quite embarassing but im going to post it for a future lost soul:

In my case it was two instances of vue running at the same time by mistake.

**Comment by msambarino** [comment]
yeah that was the issue for me as well, sorry i hadn't seen your question sooner

**Comment by gauravgavhane05** [comment]
> Closing as this was an error on my part.

How u solved the error. As I am also getting same error like below:
 [Vue warn]: Error in mounted hook: "TypeError: this.addTab is not a function"

found in

---> <TabContent>
       <Signup> at src/views/Signup.vue
         <App> at src/App.vue
           <Root>
