### ISSUE TITLE
Index type definition has no default export

### ISSUE THREAD

**Issue by seanbailey28** [cristijora/vue-form-wizard#238]
Get the following error whenever trying to follow the component registration steps in documentation:

>  "/node_modules/vue-form-wizard/types/index" has no default export

**Comment by seanbailey28** [comment]
Managed to fix my local version by slightly editing the index type definition to look like this:

`import Vue from 'vue'
import { PluginFunction } from "vue";

export function install (vue: typeof Vue): void

import { Wizard } from './FormWizard'
import { Tab } from './TabContent'
import { Step } from './WizardStep'

export class FormWizard extends Wizard {}
export class TabContent extends Tab {}
export class WizardStep extends Step {}

declare class VueFormWizard {
    static install: PluginFunction<never>;

    FormWizard: FormWizard;
    TabContent: TabContent;
    WizardStep: WizardStep;
}

export default VueFormWizard;`

I'm very new to both typescript and vuejs though, so I'm aware this might not be the proper "fix".

**Comment by dnasir** [comment]
You should post a PR for this. I ran into the same situation, and it doesn't make sense for me to edit the type definition that came with the package, since my build server will simply pull the package in via NPM and I'll run into the same problem there.

**Comment by aep** [comment]
@dnasir's version works for me. how do you apply this without modifying node_modules?
