### ISSUE TITLE
before-change to pass current and destination index

### ISSUE THREAD

**Issue by DelfsEngineering** [cristijora/vue-form-wizard#24]
I see only the `on-validate` method hook will pass the index of the current tab. But What if I want to know where the user is going so I can later do a server side validation? 

The `before-change` does not pass any of this information but would seen is the correct hook for this information.

Is it possible to know the source and the destination tab index's from any other methods?

**Comment by cristijora** [comment]
Indeed, there is no way to know that. You can access the current tab index via refs `this.$refs.formWizard.activeTabIndex` but you don't have access to the destination tab and it might be hard to do that since the validation happens first, the `before-change` is executed then the tab is changed. If the validation fails, there is basically no destination tab.

**Comment by DelfsEngineering** [comment]
Thanks. 
Is there ever a reasons to use the validation hook over the before-change one?

It seems they are called one after the other anyways.

**Comment by cristijora** [comment]
Well before change is a method dedined by the user while the validation hook is an event which is emitted once the validation of before change fails or passes. Since before change can by async/promise then on-validated hook is called later after the async execution of before change

**Comment by cristijora** [comment]
So far `on-change` event has been added 
Usage:
`@on-change="handleTabChange"`
```js
handleTabChange(prevIndex, nextIndex){
 // your logic here
}
```
However this does not prevent tab switching. If you want to do some async validations this would still not prevent tab switching. Hopefully this help a bit at least.

**Comment by mehranrasulian** [comment]
Already using `this.$children[0].activeTabIndex` in the callback passing to `:before-change` prop  so I can access the current index.

Wish there was a way to pass parameters to the callback of `:before-change`. I think this should work but not sure about the result.

```jade
tab-content(:before-change="validateItem.bind(item)")
```

```javascript
new Vue({
    methods: {
        validateItem(item) {
            // my logic
        }
    }
})
```

**Comment by cristijora** [comment]
@mehranrasulian That's a good suggestion actually. What's the item in your case ? I'm thinking whether it's better to bind form-wizard's context when calling this validation method so you could do something like
```js
 validateItem(item) {
     console.log(this.activeTabIndex)
 }
```

**Comment by cristijora** [comment]
@mehranrasulian Have you tried
`:before-change="()=>validateItem(item)"` 
This should work. Here is a fiddle. https://jsfiddle.net/bt5dhqtf/620/ Open the console and see that the parameter is passed to the method.

**Comment by mehranrasulian** [comment]
@cristijora Good idea, didn't even though about it !!! I'll try it on my project as well soon ^^

**Comment by cristijora** [comment]
I think we can close this since, there is the fiddle example which works and suits your use case.

**Comment by mehranrasulian** [comment]
It's fine, thank you !

**Comment by Jossnaz** [comment]
@cristijora just saying, when i try to do this:
```
    <form-wizard @complete="onComplete"
                 @change="handleTabChange"
                 color="gray"
                 error-color="#a94442"
...

      <template slot="footer" slot-scope="props">
        <div class="quifu-footer">
          <wizard-button :style="props.fillButtonStyle">Cancel</wizard-button>
          <wizard-button @click.native="props.prevTab()" class="qifu-form-prev"  v-if="buttonPrevDisplay" v-html="buttonPrevText"></wizard-button>
          <wizard-button @click.native="props.nextTab()" class="qifu-form-next"  v-if="buttonNextDisplay" v-html="buttonNextText"></wizard-button>
        </div>
      </template>

    </form-wizard>

```


This won't work and is giving me a head time:

`app` has the wrong scope when called like this
```
 methods: {
      handleTabChange: function (prevIndex, nextIndex) {
        let app = this;
        console.error('app.buttonNextText: ' + app.buttonNextText);
        console.error('prev: ' + prevIndex);
        console.error('next: ' + nextIndex);
        if(nextIndex == 0){
          app.buttonNextText = qifu_loco.btn_txt_tab1;
        }else{
          app.buttonNextText = qifu_loco.btn_txt_default;
        }
        if(nextIndex >= 1){
          app.buttonPrevDisplay = true;
        }else{
          app.buttonPrevDisplay = false;
        }
        if(nextIndex == 2 ){
        }
        console.error("tab changing :DD");
      },
```
