### ISSUE TITLE
Form Wizard children validation

### ISSUE THREAD

**Issue by monday9393** [cristijora/vue-form-wizard#245]
Hi cristijora, good morning, I am using your vue-form-wizard(I like it) for study and I need some help, I am not going to share code(it is messy like a playground) here because I am a newer(noob) programmer, but if you want to share some come feel free to share it. Well, I have a Wizard Form(Dad) and I have a child component(Kid), a step in your form, my Kid is using vuelidade(this is a great plugin, i love it) to validations, I would like that Kid get when someone clicked the button next-step and a validation by yourself, if validation is okay -> next step, if not, stay on the first step(Kid). Anyway, I would like to know if I get the think, because my code is not working :c (I read your documentation many time) . My Kid needs to listen to a emit from Dad when someone clicked the button, my Kid will return a object or a Boolean to Dad, the Dad will receive the new information and if it is Okay he will go to the next step? Do I need to do my Kid return a new promise? I am sorry for boring you and my english, I am not native.

**Comment by LiamMoorcroft** [comment]
My suggestion monday, as a starting point - check out this example of using the `:before-change` handler which is fired before a step change occurs.

http://vuejs.creative-tim.com/vue-form-wizard/#/?id=call-a-function-before-tab-switch

**Comment by cristijora** [comment]
Hey @monday9393 
@LiamMoorcroft pointed to the right examples. `:before-change` is a function that should be attached to `<tab-content>` and it should return either a boolean or a promise that resolves with a boolean.

You can check Readme of the repo. There are many examples including vuelidate example :) https://jsfiddle.net/CristiJ/bt5dhqtf/1119/

It's a bit ugly because back then there was no codesandbox but the idea is that you have a `validate` method inside each step component and you trigger it when going to next step via `:before-change`

```html
<tab-content :before-change="()=>validateStep('step1')">
  <step1 ref="step1"></step1>
</tab-content>

validateStep(name) {
      var refToValidate = this.$refs[name];
      return refToValidate.validate();
}
``` 

// Inside step 1 component you would have 
```js
validate() {
      this.$v.form.$touch();
      var isValid = !this.$v.form.$invalid
      this.$emit('on-validate', this.$data, isValid)
      return isValid
}
```

**Comment by monday9393** [comment]
Hi @LiamMoorcroft and @cristijora, I have forgotten to mention that I am using vue-router, I have tried the Async methods and now I see that yours solution seems more simple and convenient, I think that I can't uses references into tab-content, I will try but I am not sure, If I can't use reference like yours way, I will try to send a String in the props and use that String to make a reference. Do you guys think that is a bad design code?

**Comment by LiamMoorcroft** [comment]
@monday9393 - Without seeing your workings it hard to say whether you are on the right tracks or not, but what you are suggesting doesn't sound to crazy.

If your project is growing in size I might suggest if you haven't already taking a look at [VueX](https://vuex.vuejs.org/en/intro.html) for centralising all your application state, which you could then reference anywhere for use in your validation situation. 

However @cristijora may have a more insightful approach.

**Comment by monday9393** [comment]
Hi guys, it is me again, I made this tiny project(does not have bulma, buefy or css) using the modules that I am using [Code Here](https://codesandbox.io/s/8n3pz97xm2), my other code is a messy(I just play everything I can), in this code I am using vue-router, vuelidate and vue-form-wizard, if you see you are going to find a vuelidate in the formOne, my goal if possible, it is use a function inside formOne to validade his own data and tell to the Wizard that it is okay to proceed, when someone click the button. I will try those things you guys said above tomorrow morning. Good night and thank you.

**Comment by monday9393** [comment]
Hi again, the way you guys said is working! I made two components and use in the first step references, I still use route but I removed the **router-view tag** and the address bar is still showing the route [Code here](https://codesandbox.io/s/38k5kk3wk6).
Thanks @LiamMoorcroft and @cristijora.
