### ISSUE TITLE
Documentation and github.io links are broken

### ISSUE THREAD

**Issue by Sergeon** [cristijora/vue-form-wizard#248]
The github.io page that appears at the readme start is broken. 
The link is:
https://cristijora.github.io/vue-form-wizard/#/

When I visit the page I'm redirected to:
https://demos.creative-tim.com/vue-form-wizard/#/

which shows a 404.

Also, the documentation link at the end of the `readme.md` is broken (in fact, the link points to the aforementioned github.io page).

**Comment by cristijora** [comment]
Hi @Sergeon Sorry for that. I had a CNAME setup earlier which did some redirects. It took a while until it was changed back and therefore the links didn't work this weekend. It's fixed now.
