### ISSUE TITLE
activeTabIndex doesn't change when switching tab via the url (using view-router)

### ISSUE THREAD

**Issue by IAMine2424** [cristijora/vue-form-wizard#25]
**Problem:**
when you visit the page via a `vue-router` route, the right component is shown, but the active highlighted tab is still the first tab.

so `"activeTabIndex"` isn't updating when changing tabs trough a URL, only when changing tab with the "next" and "previous" button or directly clicking on a tab step (the icons) on top.

**Reproduce:** 
this is the example in the docs: https://jsfiddle.net/bt5dhqtf/267/ when opening local (not in a fiddle) try navigating directly to a route that isn't the first step. you'll notice that the right component is shown but the wrong tab step icon thingy is highlighted.

excuse me for my english.. 

btw, I want to help if needed :)

_See Picture: the route is /user, that's the second step. the right component is shown but the first tab is highlighted_

![image](https://user-images.githubusercontent.com/8819595/27714872-e45dcc68-5d33-11e7-8f08-6246c2e2ed66.png)

**Comment by cristijora** [comment]
Hi @IAMine2424 I am currently re-writing form-wizard to jsx so I can have more control over the rendering process. After I finish that part, you can do a PR. I think this is already is implemented in the dev branch anyway

**Comment by cristijora** [comment]
@IAMine2424 since form-wizard supports some pre-validations, would we want a route change if the forms are not valid ?

**Comment by hackel** [comment]
Was this ever fixed?  I'm customizing my footer based on `activeTabIndex`, but whenever I navigate directly to the route, `activeTabIndex=0` (instead of 1).  Reviewing the code, it doesn't look like it ever gets synchronized with the route on initial load.
