### ISSUE TITLE
Child component validation and event

### ISSUE THREAD

**Issue by aredev** [cristijora/vue-form-wizard#26]
Hi all,

I was using the wizard component but stumbled on a issue. I have the wizard with multiple steps. Each step is presented in a separate component. This component is responsible for the validation, followed by making a post request to the server. I capture the tab change event with the before-change handler, here is the issue. The before-change handler returns the result of the validation, however in my case the child component does this. A child can only communicate with its parent using events. But if I create an event handler for this 'validation' event, then this will be a separate method which cannot communicate with the before change handler. 

I thought of several (bad) ideas (eg. using a setInterval to wait until the validation event handler marks a variable in the parent component, did not really see how Promises could help but maybe they can?), but I just could not think of a solution. I do not want to put all the logic in the parent component, as this would make it very unmaintainable.

Here are some conceptual snippets: 

In the parent component

```
<form-wizard @on-complete="onComplete"
                                 shape="tab"
                                 title=""
                                 subtitle=""
                                 :validateOnBack="true"
                                 color="#9b59b6">
                        <tab-content title="Basic details"
                                     icon="fa fa-info" :before-change="submitFirstStep">
                            <first-step :step="step" @stepCompleted="stepCompleted" @created="storeSurroundingId"></first-step>
                        </tab-content>
...
```

The ```submitFirstStep``` method just changes the step property. The ```first-step``` component watches this property and handles upon a change. 

The watch method in the ```first-step``` component:

```
watch: {
    step(value){
        //Check if value is OK

       //Perform validation

       //Store at server

       //Emit stepCompleted  if succeeded or if error occured
    }
}
```

And finally:

```
submitFirstStep(data){
    this.step = //Change accordingly

    // The child should start now, but I am not sure when it has finished ...

    //return value based on the child here
}

stepCompleted(data){
     //Validation and error data is received here...
}

```

Hopefully anyone can help. Really love the package, but this is a little hard out of the box :(

Edit 1: Fixed some Markdown issue.

**Comment by cristijora** [comment]
@aredev I will try to re-create a jsFiddle and start from there.

**Comment by cristijora** [comment]
Here is the solution I came up with https://jsfiddle.net/bt5dhqtf/591/

In your submit step you change the step which trigger your server request and after that return a promise. The catch here is that promise listens for a local event in your parent component. When that even is emitted, the promise resolves/rejects accordingly.

```js
submitFirstStep() {
	this.step++
        return new Promise((resolve,reject)=>{
          this.$on('step-validated',(value)=>{
            resolve(value)
          })
        })
      },
```

In your stepCompleted event handler you simply emit the local event mentioned above
```js
stepCompleted(data) {
  //Validation and error data is received here...
    this.$emit('step-validated',data)
 },
```
So you have a pretty simple solution. 
Trigger `before-change` and return a promise which listens to a local event -> make your server request -> emit the event from your component to the parent - > listen for the event in the parent component -> emit a local event in the parent component which will resolve the promise. 

This way you don't have to do any workarounds and you have all your data in place based on which you can decide whether to restrict or allow going to the next step! Hope it helps
