### ISSUE TITLE
No Form Wizard - Errors

### ISSUE THREAD

**Issue by movepixels** [cristijora/vue-form-wizard#28]
I followed the guide, pretty straight forward but I am getting many errors.
[Vue warn]: Error when rendering component <form-wizard> at C:\work\vue-tab-wizard\src\components\FormWizard.vue: 

I dont even have a C:\work folder ???

And:
Uncaught TypeError: Cannot set property 'active' of undefined

I used the npm and tried straight download, both show the same errors.

Global and local registration.

Sidenote:
The docs state import 'vue-formwizard/dist/vue-form-wizard.min.css'
where it should be import '**vue-form-wizard**/dist/vue-form-wizard.min.css', missing the dash between formwizard

**Comment by cristijora** [comment]
Hi @movepixels. Can you please provide your setup (component registration and usage) and maybe a stack trace/screenshot of this error 'active' of undefined?

**Comment by cristijora** [comment]
Could you please try the latest 0.6.1 version and see if the error reproduces? The private paths at least should be removed

**Comment by movepixels** [comment]
Ok thanks, just grabbed the 0.6.1 version, the C:\work folder error is gone,
Using Vue 2.0.7
![untitled-1](https://user-images.githubusercontent.com/1903217/28148461-63f4abe0-6761-11e7-835d-2e13f7b1dd3f.png)

**Comment by cristijora** [comment]
You might want to upgrade to at least vue 2.1.5. I need some time to figure it .

**Comment by cristijora** [comment]
Latest version uses scoped slots which requires vue > 2.2.0, therefore closing this issue as it does not persist when vue version is higher than 2.2.0. Let me know if you have any updates after upgrading vue version.

**Comment by amsanket22** [comment]
I have 0.6.2 now but it gives error on some events not while shuffling the tabs. i think it has some problems with routes. please help. everything works fine but it just gives error in console - "[Vue warn]: Error in destroyed hook: "TypeError: Cannot set property 'active' of undefined"

**Comment by cristijora** [comment]
Can you show the code please? Maybe reproduce in a fiddle?

**Comment by amsanket22** [comment]
Yes definitely, I will try to do it. but actually I am using electron, and I am using vue router, it occurs when I change the route, suddenly it shows that error.

**Comment by cristijora** [comment]
@amsanket22 I found the error myself when working on another project. It has been fixed and 0.6.3 does not contain the error anymore. It occurred when navigating to another page. I had some operations in the beforeDestroy hook which needed some more checks.

**Comment by amsanket22** [comment]
@cristijora Yes, Update resolved my issue, thank you so much. I liked your support.

**Comment by vishal-gadhiya** [comment]
@cristijora I found this error when using laravel inertial js with vue-form-wizard.
Can you help me please.
![image](https://user-images.githubusercontent.com/53233027/119222859-073b5100-bb14-11eb-81e1-651c6606b7f4.png)
