### ISSUE TITLE
How to disable the click event on nav pills?

### ISSUE THREAD

**Issue by alex996** [cristijora/vue-form-wizard#29]
The form that I'm building requires that the users cannot go back to a previous step. I used a little trick to remove the "Back" button: `<template slot="prev"></template>`. However, I couldn't find a way to disable the nav pills (i.e. the circle steps at the top) from allowing the user to navigate back. How can I approach this?

P.S. On a side note, I used `<tab-content title="" icon="-">` to remove the title and the icon. `icon=""` alone does not seem to work. Is there a better way? I'm using the [basic demo example](https://jsfiddle.net/bt5dhqtf/97/).

**Comment by cristijora** [comment]
@alex996 I'm on a little vacation and cant really provide an example or a full answer intil the end of this week. Regarding your second question, placing empty strings as icon and title should be enough to display an empty step.
Regarding your first question, for now, you can't really prevent the steps from having click handler events. Maybe a scoped slot can be added or eventually another prop

**Comment by alex996** [comment]
@cristijora Thanks for answering! I'll take a look at the source code, and maybe I could write a PR for this based on your suggestions.

As for the icons, it seems that by default it puts numbers inside nav pills (i.e. 1,2,3, etc.), whether you provide the prop `icon=""` or leave it out altogether. Here's a copy of the [basic demo](https://jsfiddle.net/bt5dhqtf/658/) to show this... But then, this isn't as important, so no worries :) Enjoy your holidays!

**Comment by cristijora** [comment]
@alex996 as small as this requirement seems, I had to make couple of changes to make this possible but in the end it lead to cleaner code and a more modular wizard.

 Here is an example https://jsfiddle.net/bt5dhqtf/705/ (not published to npm yet)
The step is exposed via a component which accepts 3 props. You can look in the source
Usage:
```html
<template slot="step" scope="props">
        <wizard-step :tab="props.tab"
        :transition="props.transition"
        :index="props.index">
        </wizard-step>
</template>
```

Besides the things from above, you have available `navigateToTabMethod` in `props` which is used in the default version for the click event on the step/ nav pills.
If you still want to add the click handler, you could: 
```js
 <wizard-step :tab="props.tab"
        :transition="props.transition"
       @click.native="props.navigateToTab(props.index)"
        :index="props.index">
</wizard-step>
```

Note: this is working only in vue >2.2.0

**Comment by cristijora** [comment]
See release notes from the last release for additional details https://github.com/cristijora/vue-form-wizard/releases/tag/v0.6.2
and the updated docs https://cristijora.github.io/vue-form-wizard/#/?id=step-slot

**Comment by AkmalSab** [comment]
use this css instead

.vue-form-wizard .wizard-nav-pills a, .vue-form-wizard .wizard-nav-pills li{
  cursor: not-allowed;
  pointer-events: none;
}
