### ISSUE TITLE
Error: You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by retrogradeMT** [cristijora/vue-form-wizard#3]
I am gettting this error:   .../node_modules/vue-form-wizard/dist/vue-form-wizard.min.css Unexpected token (14:83)
You may need an appropriate loader to handle this file type.

Do you know which loader is needed?

**Comment by SirRafaMedina** [comment]
In my case, I´m using css-loader:

`  { test: /\.css$/, loader: 'style-loader!css-loader'},"`

**Comment by cristijora** [comment]
@retrogradeMT Can you tell a bit more about your setup ?
You can also import the css directly into a html page with a `style` tag
```html
<link rel="stylesheet" href="vue-form-wizard.min.css">
<script src="vue-form-wizard.js"></script>
```

**Comment by retrogradeMT** [comment]
I think I will just use the style tag approach for now but I'd be happy to help get to the bottom of this error.   I'm using Laravel elixer 6, webpack and vue 2.1.6

I've got the following loaders installed:  style, stylus, css, vue and sass

**Comment by cristijora** [comment]
Did you import other css files with `import` so far?

**Comment by retrogradeMT** [comment]
No, I have not

**Comment by cristijora** [comment]
Try searching for this issue in the [laravel community](https://gitter.im/laravel/laravel?source=explore) 
as it is not related to vue-form-generator. I don't know the laravel setup very good unfortunately so I can't help you here. [stackoverflow related to this](http://stackoverflow.com/search?q=import+css+from+node_modules+laravel)
