### ISSUE TITLE
Transition effect for steps - example

### ISSUE THREAD

**Issue by Chinese1904** [cristijora/vue-form-wizard#30]
Hi!

I am struggling to figure out how to use transitions. I was thinking about using a simple bounce-out-left transition and from the docs I can see

```javascript
  transition: {
    type: String,
    default: '' //name of the transition when transition between steps
  },
```

How exactly do I implement it into my Vue app?

Is this a working example?

```javascript
Vue.use(VueFormWizard, {
    props: {
        transition: {
            type: String,
            default: '' //name of the transition when transition between steps
        }
    }
});
```

I can't find any documentation on this and how it functions. If I define default, do I define it with the CSS class name for the transition?

Is there any way you could provide a working example of a transition? I would appreciate that so much!

**Comment by cristijora** [comment]
@Chinese1904 `transition` is a prop for the wizard. It will not work as you wrote.
Please take a look at https://vuejs.org/v2/guide/transitions.html#Transitioning-Single-Elements-Components to understand how transitions work in vue
The usage would be `<vue-form-wizard transition="fade">.... </vue-form-wizard>

And then, here is an example https://jsfiddle.net/bt5dhqtf/664/ with fade animation

With bounce animation https://jsfiddle.net/bt5dhqtf/671/ (personally don't quite like the effect)
Another example with "pulse" animation which looks smoother to me https://jsfiddle.net/bt5dhqtf/672/
