### ISSUE TITLE
Using sensible z-index values

### ISSUE THREAD

**Issue by jpnut** [cristijora/vue-form-wizard#33]
**Problem**
The current z-index values used for the default styles are seemingly arbitrary - see [here](https://github.com/cristijora/vue-form-wizard/blob/master/src/assets/form-wizard/_navs-pagination.scss#L24), [here](https://github.com/cristijora/vue-form-wizard/blob/master/src/assets/form-wizard/_wizard-card.scss#L57), and [here](https://github.com/cristijora/vue-form-wizard/blob/master/src/assets/form-wizard/_wizard-card.scss#L80).

As far as I can tell, removing these z-index values has absolutely no impact on the appearance of the navigation and header. I'm wondering if there is a good reason for these values? Otherwise I'd be more than happy to submit a PR with the relevant changes.

**Comment by cristijora** [comment]
@jpnut A PR would be very welcome. Indeed, the css part is not the best and could be improved. I don't think there is a reason for these values since initially I started with the css from https://www.creative-tim.com/product/paper-bootstrap-wizard and adjusted it along the way

**Comment by jpnut** [comment]
Sure thing! To be honest the css is the least of my concerns - it's very straightforward to roll your own solution, but I personally quite like the default styles provided, and would like to use them in my projects - the only thing stopping me was the z-index! I'll submit a PR today or tomorrow, depending on when I get the time.

Thanks a lot for a great package, your work on this is greatly appreciated!

**Comment by cristijora** [comment]
Thanks for the kind words. The goal for me, would be to have something like in my other component https://github.com/cristijora/vue-tabs#theming where you can easily make a theme a make it look different/personalized quite easy.
