### ISSUE TITLE
How to fire onComplete when submitting using enter key

### ISSUE THREAD

**Issue by vxzry** [cristijora/vue-form-wizard#34]
Clicking the finish button fires my ajax request from my onComplete function
but pressing enter key just submits the form normally

**Comment by cristijora** [comment]
@vxzry If you are familiar with scoped slots, you can do this with the latest 0.6.2 version
Here is an example
https://jsfiddle.net/bt5dhqtf/724/

You have to wire a couple of things yourself but then you have control over what actions to do when interacting with the buttons :)

**Comment by vxzry** [comment]
This is what im trying to do 
https://jsfiddle.net/dgkej2ke/
what should i do to submit the form through the on-complete method?

**Comment by cristijora** [comment]
Not quite understanding what you want there. You want to submit the form from the last step or the first step?

**Comment by vxzry** [comment]
Ohh I'm sorry. I wrapped my form-wizard inside a form element and I was wondering how I could use the complete function from the form wizard to handle the submit event of my form aside from clicking the finish button. Do I need to create a different function outside my vue instance or is there something inside vue-form-element that does this kind of thing? Im really sorry for all the trouble.

**Comment by cristijora** [comment]
I think I understood. I simplified the example a bit
https://jsfiddle.net/dgkej2ke/17/

You can call submit on your form element https://www.w3schools.com/jsref/met_form_submit.asp
`this.$refs.myForm.submit();`

**Comment by vxzry** [comment]
Ohhhhh right 👍 Thank you so much! I forgot about submit prevent. I could use that. Thank you.
