### ISSUE TITLE
Support other icons than themify

### ISSUE THREAD

**Issue by Sobient** [cristijora/vue-form-wizard#38]
From the looks of it, Themify icons are used. However, for users that want to support material icons or font awesome, there doesn't seem to be a way to do that (yet).

**Comment by cristijora** [comment]
Form-wizard will work with any icons that can be used as classes 
Here is an example with font-awesome icons
https://jsfiddle.net/bt5dhqtf/891/

**Comment by Sobient** [comment]
Aye, I actually found that out after using this module. Hence:

`<tab-content title="Choose customer" icon="fa fa-search">` worked flawlessly. Thanks for the quick response!

**Comment by cristijora** [comment]
No problem. Happy coding!
