### ISSUE TITLE
Support for sizing the step indicators

### ISSUE THREAD

**Issue by Sobient** [cristijora/vue-form-wizard#39]
For this it seems that there is no property to control the size of the step indicators, unless one overrides them with CSS. 
A "size" attribute with values like "xs, sm, md and lg" that would resize the circles and the icons inside, would go a long way to remedy this and also allow for quite the flexibility. 

I've attached some images to illustrate what I mean (these are just examplary values)

## Extra small
(Size of each step is 40x40, font-size: 1rem)
![bilde](https://user-images.githubusercontent.com/706874/29819059-45ae1f94-8cbf-11e7-821e-d453e257ac05.png)

## Small
(Size of each step is 50x50, font-size 1.4rem)
![bilde](https://user-images.githubusercontent.com/706874/29818921-af09d74a-8cbe-11e7-8991-76fb10ed846a.png)

## Medium
As it is today.

## Large
(Size of each step is 70x70, font-size 2rem)
![bilde](https://user-images.githubusercontent.com/706874/29818973-dc57d9cc-8cbe-11e7-802b-a745084c2129.png)

**Comment by cristijora** [comment]
Greatly formatted issue. Very clear and straight to the point!
Will try to find some time this week and add a new prop for this.

**Comment by cristijora** [comment]
I made a fiddle for the latest changes
https://jsfiddle.net/CristiJ/bt5dhqtf/924/

It might not work right away because of browser cache so you might want to open it in incognito or something like that.

**Comment by Sobient** [comment]
Very nice. Has this been pushed to NPM?

**Comment by cristijora** [comment]
Not yet, Will publish it today

**Comment by cristijora** [comment]
Release [0.6.5](https://github.com/cristijora/vue-form-wizard/releases/tag/v0.6.5)
