### ISSUE TITLE
[Question] How is @on-validate supposed to work?

### ISSUE THREAD

**Issue by hydraheim** [cristijora/vue-form-wizard#41]
Looking at the docs, there is very little outlining how this directive works. What does it run through and what alters its outcome? Hence:

```
**Template**
  <form-wizard @on-complete="onComplete"
                  @on-loading="setLoading"
                  @on-validate="handleValidation"

**Methods**
        handleValidation: function(isValid, tabIndex){
           console.log('Tab: '+tabIndex+ ' valid: '+isValid)
        },
```
Would always yield "isValid" as true. 

Reference: https://cristijora.github.io/vue-form-wizard/#/?id=async-validation

**Comment by cristijora** [comment]
https://jsfiddle.net/bt5dhqtf/927/

`on-validate` is called whenever a certain step has a `before-change` function and this function is executed.
It's basically called whenever there is a validation of a certain step with the result of the validation.

**Comment by hydraheim** [comment]
Right, it seems your example uses some sort of third-party form schema generator and validator, which upon you use the result of validate() to further propagate your handleValidation outcome. 

At the moment we're using bootstrap-vue to generate the forms, with Vuelidate as a validator. Unsure if the reactive validation object Vuelidate generates can be directly connected without explicitly checking each required attribute explicitly. Like so:

**Template**
```<tab-content title="Setup" class="row" icon="fa fa-2x fa-info" :before-change="() => validateStep(1)">```

**Script**
Validations
```
  validations: {
    selectedCustomerId: {
      required,
      numeric: numeric
    }
  }
```
Methods
```  validateStep: function (d) {
      if (d === 0) {
        if (!this.$v.selectedCustomerId.$invalid) {
          this.formError = false
          return true
        } else {
          this.formError = true
          return false
        }
     }
```
Which is, tbh, fairly unelegant.

**Comment by cristijora** [comment]
What about Validation groups ?
https://monterail.github.io/vuelidate/#sub-validation-groups

**Comment by cristijora** [comment]
@hydraheim Here is a basic fiddle for Vuelidate.
https://jsfiddle.net/CristiJ/bt5dhqtf/952/
It's not very good looking because I made it in like 5mins but you can have form groups and validate a "group" of inputs, the group being the set of inputs from one of your "tab-contents"

**Comment by hydraheim** [comment]
Thanks for looking into that.

Already looked at validation groups, but referencing the [docs ](https://monterail.github.io/vuelidate/#sub-validation-groups ) there doesn't seem to be any support for validating several isolated groups (which would correspond to step 1, step 2, and so on). There might be, but the docs leaves some things to be desired.

**Comment by cristijora** [comment]
Well I think you should have 1 group per step :) 
If you want to validate 2 groups I guess you should create 2 and validate them together in a function
Here is the validation for one group
```js
this.$v.validationGroup.$touch();
return !this.$v.validationGroup.$invalid
```

For 2 or more you can save them in some array 
```js
this.$v.validationGroup.$touch();
this.$v.validationGroup2.$touch();
return !this.$v.validationGroup.$invalid && !this.$v.validationGroup2.$invalid.
```

Anyway, those are vuelidate specific details. Form-wizard was not built with a specific validator library in mind. It exposes the `before-change` functions which can be used to handle validation regardless of library. So far I've made wizards with vee-validate, vue-form-generator and element-ui with no issues, so I guess you can do it with vuelidate as well. Just figure out how to trigger validation manually for a set of inputs and you're good to go.

**Comment by cristijora** [comment]
I made a more complete fiddle @hydraheim 
https://jsfiddle.net/CristiJ/bt5dhqtf/1119/ and will add it to the other examples from the docs.

**Comment by hydraheim** [comment]
Will delve into the example once we revisit this for refactoring. Highly appreciated for the hard work here, rare for issues that reside outside the main component. This is above and beyond, sir.

**Comment by cristijora** [comment]
Glad I could help @hydraheim As a side note, the example from above was added to the readme. Maybe it helps other people too. Also I used bootstrap in it to keep it simpler but shouldn't be an issue. Let me know if it works out in the end and if you had to do other changes so I can update my example as well. I didn't use vuelidate too much, so I might not know the best practices for it yet.

**Comment by grex22** [comment]
@cristijora - Is there any way I could plesae see your integration you mentioned with vee-validate? I've spent a couple of hours trying to get it to work and I'm about out of ideas :/

**Comment by malbrecht0792** [comment]
@cristijora I'm also not able to get the vue-form-wizard to work with vee-validate. The solution you mentioned would be much appreciated!
