### ISSUE TITLE
Cancel Button

### ISSUE THREAD

**Issue by alienatorZ** [cristijora/vue-form-wizard#43]
I would like to request a way to cancel out of the wizard.

Maybe in addition to Next and Back there Is a Cancel Button.

**Comment by cristijora** [comment]
Hey @alienatorZ There was an issue about buttons
Here is an example of how you can add buttons near "Next" or "back" buttons
https://jsfiddle.net/CristiJ/uppptbh0/11/

You can also fully customize  the footer section which is harder to do but then you could arrange how you want
https://jsfiddle.net/bt5dhqtf/717/

**Comment by alienatorZ** [comment]
Ok Thanks!

That works!
