### ISSUE TITLE
[Question] How do one manipulate the step index?

### ISSUE THREAD

**Issue by Sobient** [cristijora/vue-form-wizard#44]
Basic case in point: 
- User follows the form wizard to complete an article.
- After the form has completed, the user is presented a selection of actions, one of which is to create another  article. 
- User clicks "Create another article" is sent back to the first step of the form vue wizard.

**Comment by cristijora** [comment]
@Sobient Currently you can do this only via `$refs`

```js
 this.$refs.wizard.navigateToTab(0)
```

Internally the wizard has ` navigateToTab` methods which accepts an index. This method is the same method used when clicking on a step.
https://github.com/cristijora/vue-form-wizard/blob/master/src/components/FormWizard.vue#L236

Here is an example also
https://jsfiddle.net/bt5dhqtf/982/

Complete the steps and on the last step there is a "Start again" button which resets the data and send the wizard to the first step.

**Comment by Sobient** [comment]
Thanks, that seems to do the trick.
