### ISSUE TITLE
Reset wizard

### ISSUE THREAD

**Issue by StevenHill2500** [cristijora/vue-form-wizard#47]
Hi there, this is my first post on Github, i apologise in advance if this is the wrong place, 

I have checked the documentation, but is there any function to reset the wizard back to start (the first point)? 

My issue is that when a user clicks into an "item", he is presented with the wizard. IF he goes through a couple steps and goes back to a different "item", the last stage they were at remains. Ideally every time I go into an "item", the wizard should be back at the start.

I hope this makes sense,

Thanks

**Comment by cristijora** [comment]
Hi @StevenHill2500 I think there was an issue for this already.
#44 

Here is a fiddle 
https://jsfiddle.net/bt5dhqtf/982/

Go to the last step and there is a start again button which basically does this.
```js
restart: function() {
      this.model = {
        firstName: '',
        lastName: '',
        email: '',
        streetName: '',
        streetNumber: '',
        city: '',
        country: ''
      }
      this.$refs.wizard.navigateToTab(0)
 },
```

`this.$refs.wizard.navigateToTab(0)` Will navigate to the first step.

**Comment by StevenHill2500** [comment]
Hi @cristijora 

Thank you ever so much! it works perfectly :) 

You can mark this issue as resolved / closed. 

Thanks again

**Comment by ReynerHL** [comment]
Is there anyway to reset the wizard to its initial state? I mean, how can we mark all those steps already visited as not visited again.
