### ISSUE TITLE
Steps without restrictions

### ISSUE THREAD

**Issue by SirRafaMedina** [cristijora/vue-form-wizard#5]
Is there a way to enable to jump between steps?

I'd like to jump from the first to the last one?
 I know can do it if I pass all the step with the "Next" button or setting the  :start-index="lastIndex" but i'd like having without restrictions

**Comment by cristijora** [comment]
Interesting idea. I might add a special slot for this so it's possible to do that. What do you mean by without restrictions? Ignore beforeChange calls ?

**Comment by cristijora** [comment]
Update 
You can use a ref and change tab in the following way
```js
this.$refs.wizard.changeTab(fromIndex, toIndex)
//This will switch from first tab to 4th tab
this.$refs.wizard.changeTab(0, 3)
```

**Comment by SirRafaMedina** [comment]
I mean to be able to skip to any step.
Example, we have a form with three steps and we saved all the info.
If somebody comes back and wants to update its info just in the 2nd step, let it click on it without validate the info in the first one.
In the fiddle, the solution could be this:
```javascript
  gotToLastStep: function(){
     this.$refs.wizard.changeTab(0,3)
     this.$refs.wizard.changeTab(0,0)
   }
```

**Comment by cristijora** [comment]
From your use case, I would rather make the `:start-index="2"` and after that you can click on any of the upper steps and go back to the step you want.
