### ISSUE TITLE
Customize Navigation

### ISSUE THREAD

**Issue by zhang-yafei** [cristijora/vue-form-wizard#51]
My site needs to be able to run on the mobile，At this time the top navigation icon is too big.

I want to hide the navigation，but keep tap-content and button.
![navigation](https://user-images.githubusercontent.com/19721688/30893001-54e0ed6e-a36e-11e7-985f-b1cb14b74b86.png)

**Comment by cristijora** [comment]
Not sure I fully understand the issue but you can make the navigation icons smaller
https://jsfiddle.net/CristiJ/bt5dhqtf/924/

**Comment by zhang-yafei** [comment]
yes,I know the style.
But on the mobile side generally do not show as icon navigation,show drop-down list navigation.

I would like to know if I can customize the navigation.Such as incoming parameter jumps to the specified tap-content.May be better

**Comment by cristijora** [comment]
@zhang-yafei Could you take a look at https://github.com/cristijora/vue-form-wizard/issues/22
Is this
https://user-images.githubusercontent.com/15609894/30966915-3158b146-a478-11e7-81cd-a7edb53eb70e.png

something similar to want you need for mobile?

**Comment by zhang-yafei** [comment]
I did not use components on the phone side.
This is My effect picture
![image](https://user-images.githubusercontent.com/19721688/32598158-e87ede06-c573-11e7-834b-c84560aeddd5.png)

**Comment by cristijora** [comment]
So you used something else than form wizard?

**Comment by zhang-yafei** [comment]
yes,Mobile-side navigation more customized.
Customer gave the UI picture,So I did not use wizard on the Mobile-side
