### ISSUE TITLE
Want to write callback function on next button

### ISSUE THREAD

**Issue by rahulsingh9096806080** [cristijora/vue-form-wizard#53]
I want to write callback function next button.How can i proceed

**Comment by cristijora** [comment]
There are a couple of demos in the readme with this. You can write both callbacks or promises for each tab content https://jsfiddle.net/bt5dhqtf/105/

**Comment by rahulsingh9096806080** [comment]
in case of any callback if i am passing any value then callback is fired before click.
below is fork 
https://jsfiddle.net/xoenp468/

**Comment by cristijora** [comment]
I see. This happens because the function is basically invoked when the component is rendered.
Use an arrow function in this case.
```:before-change="()=>beforeTabSwitch(1)"```
https://jsfiddle.net/xoenp468/1/
