### ISSUE TITLE
How to access activeTabIndex in parent/sibling components?

### ISSUE THREAD

**Issue by Chinese1904** [cristijora/vue-form-wizard#55]
Hi there,

I am struggling to figure out how to use `activeTabIndex` outside of the `form-wizard` component. Is there any simple example on how to access it outside of that scope? Sorry, if this is a silly questions, I just can't come up with an answer without modifying the source code...

Chris

**Comment by cristijora** [comment]
You can use `.sync` modifier on `:start-index` and it will sync the `activeTabIndex` 
There is also an event `on-change` which is called whenever you navigate from one step to another.
