### ISSUE TITLE
The "scope" attribute for scoped slots has been deprecated

### ISSUE THREAD

**Issue by silvio-e** [cristijora/vue-form-wizard#57]
Hey!

Just want to notify that in the docs you still use the scope attribute which results in following warning: 

`(Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots.`

for example when using footer code example

`<template slot="footer" scope="props">...`

Cheers! :)

**Comment by cristijora** [comment]
Hello @silvio-e Although I am aware of the upcoming depcration, many people still use older versions of vue. Will change this after some more time so people don't have issues with scoped slots not working on older versions due to the new syntax
