### ISSUE TITLE
Many many TabContents

### ISSUE THREAD

**Issue by ChambreNoire** [cristijora/vue-form-wizard#58]
Hi,
I'm working on a rather large multi-step form (hundreds of questions) with conditional logic (steps hidden based on the responses to questions in previous steps) and 'mid-way' saving. My question pertains to the use of TabContents. As I understand it *all* the supplied tabs are rendered into the dom (barring hidden tabs). Is there a particular reason for this choice (rather than just switching out tabs whenever next is triggered) and how would one go about patching the library to only render the current tab at any given time (as in my case there are going to be loads)?
Many thanks,
A

**Comment by cristijora** [comment]
hi @ChambreNoire 
There are some technical details why all tab contents are rendered. The main reason all of them are rendered is because they are inside a `slot` and the wizard has to know the titles of all tab contents. If you really need one at a time you could try to make a fork and change https://github.com/cristijora/vue-form-wizard/blob/master/src/components/TabContent.vue#L2 to `v-if`. This may cause some issues however.

**Comment by ChambreNoire** [comment]
Thanks. I've spent some time looking at the sources and I see it now. However I'm still unsure about how one can implement step branching - by which I mean hiding/skipping steps based on data inputted during previous steps. Your asisstance would be most appreciated!
Cheers,
A

**Comment by silvio-e** [comment]
@ChambreNoire I made a simple branching with template elements based on a chosen value like:

```
<tab-content>
  // making my first choice here saved in this.choice ...
</tab-content>

// banch 1
<template v-if='choice === true'>
  <tab-content>...</tab-content>
  <tab-content>...</tab-content>
  <tab-content>...</tab-content>
</template>

// branch 2
<template v-if='choice === false'>
  <tab-content>...</tab-content>
  <tab-content>...</tab-content>
  <tab-content>...</tab-content>
</template>
```
The template elements won't get rendered.

**Comment by cristijora** [comment]
@ChambreNoire some code samples with what you have would help

**Comment by cristijora** [comment]
Closing due to inactvity
