### ISSUE TITLE
No bootstrap

### ISSUE THREAD

**Issue by packytagliaferro** [cristijora/vue-form-wizard#6]
This is just a suggestion, but i would only include the sass (or css file) needed to make this work and not the whole bootstrap css file. A lot of developers do not use bootstrap and use just mixins since bootstrap is pretty bloated and you need to overwrite a ton so when I added this component it wrecked havoc on my layouts since it included the whole bootstrap css file. You cloud maybe too just add the css to the vue component and make it scoped so it only effects that component.

**Comment by cristijora** [comment]
Hey thanks for posting this. I am vet aware of that and I started working on that earlier on but somehow left it aside so I could implement the main stuff. The bootstrap css imported in the component is a custom build which has only navs and a progress bars. My plan is to get rid of it and have the styling under the form wizard main class so it doesnt affect anything globally

**Comment by packytagliaferro** [comment]
Perfect. That would help a ton since even some of the nav stuff affects globally. I am currently stripping some stuff and making it only affect the plugin that I could post if needed. 

Cheers!

**Comment by cristijora** [comment]
You can do a PR if you wish. I can only work on this tomorrow or probably today

**Comment by cristijora** [comment]
Did some cleanup on the css. The final css bundle reduced from 40kb to 6kb. Still can be improved

**Comment by cristijora** [comment]
Please see the [new release](https://github.com/cristijora/vue-form-wizard/releases/tag/v0.3.0) We can close the issue
