### ISSUE TITLE
How to introduce a third button just beside next

### ISSUE THREAD

**Issue by skaka34** [cristijora/vue-form-wizard#60]
I want to add a third button called "Save and Exit" just beside the Next Button where an user can just fill the particular form and exit the form-wizard. ON clicking on the "Save and Exit", I want to fire an ajax call which will serialize the form data(tab-1) and save the data to DB. Also, on click of next, we should go to next tab and the data should be saved.

**Comment by cristijora** [comment]
Hi @skaka34 
There are 2 separate slots for this
https://cristijora.github.io/vue-form-wizard/#/?id=slots 
Here is a small example
https://jsfiddle.net/bt5dhqtf/1396/

Depending on your use case, you could use `before-change` as a promise and resolve it with true or false depending on your app logic. 
If you want to display the save button only after a certain step, you could use some of the exposed properties through the scoped slot https://cristijora.github.io/vue-form-wizard/#/?id=scoped-slots

For example https://jsfiddle.net/bt5dhqtf/1397/
` v-if="props.activeTabIndex > 0"`

**Comment by cristijora** [comment]
It's also possible to customize the footer with your own layout where you could introduce as many buttons as you want or perhaps other tags/html
