### ISSUE TITLE
Is it possible to change the back button color?

### ISSUE THREAD

**Issue by richpollen** [cristijora/vue-form-wizard#63]
Hi there - Is it possible to have a different coloured back button? Right now I can only set the over theme color for the steps and back / next buttons

Thanks

**Comment by wszyf2100** [comment]
yes，color，position，width，height..you can customize.

**Comment by wszyf2100** [comment]
You can see demo Customize buttons with footer slot，increase a class attribute

**Comment by richpollen** [comment]
ah right, so just override the footer slot - thanks!

**Comment by cristijora** [comment]
Hi @richpollen 
You can use the `footer` scoped slot to have full control over the footer
Here is an example which defines 3 different buttons
https://codesandbox.io/s/81j2jyk3q9

In the docs you can see which properties are sent to the scoped slots 
https://cristijora.github.io/vue-form-wizard/#/?id=scoped-slots

You have access to methods like `nextTab, prevTab` and some other properties including the default button styles.
