### ISSUE TITLE
Programmatically change index

### ISSUE THREAD

**Issue by packytagliaferro** [cristijora/vue-form-wizard#7]
Is there way to call `navigateToTab` method from the parent component? Basically so you dont have to use any buttons but call it when I get a call back (say from when stripe or my server says they have created an account). This way when I get success response it moves to the next step. 

Thanks!!

**Comment by cristijora** [comment]
You can always use a `ref` on the wizard and programatically call `changeTab` 
`this.$refs.wizard.changeTab(oldIndex,newIndex)`
https://jsfiddle.net/bt5dhqtf/316/
Notice that this won't trigger the validation methods. You can also take a look at [this issue](https://github.com/cristijora/vue-form-wizard/issues/5) which is basically the same thing

**Comment by packytagliaferro** [comment]
Perfect! I forgot to add ref to the wizard component
