### ISSUE TITLE
typescript definition required

### ISSUE THREAD

**Issue by RouR** [cristijora/vue-form-wizard#79]
Pleas, add typescript definitions

**Comment by cristijora** [comment]
@RouR I don't have too much experience with typescript so any general tips on how to do that would help a lot.

Would it be sufficient to add an `index.d.ts` file and define classes for
- FormWizard component
- TabContent component
- WizardButton component

and the component classes would be something like this 
https://github.com/ElemeFE/element/blob/dev/types/tab-pane.d.ts

**Comment by RouR** [comment]
I think yes.
I'm just studying Vue as it described in [official documentation](https://vuejs.org/v2/guide/typescript.html)
