### ISSUE TITLE
no api to hide button, no api to jump to step x

### ISSUE THREAD

**Issue by rogeronline** [cristijora/vue-form-wizard#8]

**Comment by cristijora** [comment]
Change buttons with slots: https://jsfiddle.net/CristiJ/bt5dhqtf/332/
Jump to a certain step: https://jsfiddle.net/bt5dhqtf/316/
`this.$refs.wizard.changeTab(fromIndex,toIndex)`

**Comment by rogeronline** [comment]
thanks for quick reply. didn't expect that fast:)
refs is only working inside specific React lifecycle methods, am i right?
And is that possible to disable wizard icons?

**Comment by cristijora** [comment]
To disable icons use css.
```css
.vue-form-wizard .icon {
 display: none;
}
```
A `ref` in Vue as well as in React is a reference either to a DOM element or a component which is also a DOM element. Therefore `refs` are accessible only from the moment your parent component is inserted in the DOM  (from `mounted` hook until `destroy`). You can use refs inside `mounted` or `methods` but don't recommend using them in `computed`

**Comment by rogeronline** [comment]
this ugly solution works..., 
`onComplete : function(){
	for (var i = 0; i < this.$children.length; i++) {
                if (this.$children[i].$options.name == 'form-wizard') {
                    this.$children[i].changeTab(2,0);
                }
            }

			}`

**Comment by rogeronline** [comment]
cool! thanks !!!

**Comment by cristijora** [comment]
Why not add a ref
```
<form-wizard ref="wizard">
//rest of the code
</form-wizard>
onComplete (){
 this.$refs.wizard.changeTab(2,0)
}
```

**Comment by rogeronline** [comment]
You are right!!! This is much more elegant！Sorry, did not notice that in yr first post. Thanks for your great help to a newbie!
